baseURL = "https://urlretelibera.org"
languageCode = "en"
DefaultContentLanguage = "en"
title = "URL - Rete Libera"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Url - Rete Libera"
author = "Url - Rete Libera"
description = "La rete del libero pensiero."
profilePicture = "images/urllogo.png"
keywords = ""
favicon = "favicons/favicon.ico"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
# mainSections = ["post"]
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fab fa-telegram"
title = "telegram"
url = "https://t.me/hackerbari"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/URL-Rete-Libera"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "facebook"
url = "https://www.facebook.com/urlretelibera/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/URL_ReteLibera/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "linkedin"
url = "https://www.linkedin.com/company/url-rete-libera"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Post"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Contatti"
  weight = 400
  identifier = "contact"
  url = "/contact/"
